# 图片渲染精度
renderScale: 100

# 是否开启仓库更新检查推送
checkRepo: true

# 仓库更新检查推送Cron
checkRepoCron: "* */20 * * * ?"

# 是否开启每日自动更新表情包数据
autoUpdateRes: true

# 自动更新资源Cron
autoUpdateResCron: "0 0 2 * * ?"

# 自动更新
autoUpdate: false

# 自动更新Cron
autoUpdateCron: "0 0 1 * * ?"