name: verson-close

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  sync-main-to-dev:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 同步分支
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout dev
          git reset --hard origin/main 
          git push origin dev --force 

  push-tag:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/v')
    needs: sync-main-to-dev
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 推送Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          VERSION=$(echo "${{ github.event.pull_request.head.ref }}" | sed 's|release/v||')
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin "v$VERSION"

  create-release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/v')
    needs: [sync-main-to-dev, push-tag]
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
          
      - name: 提取版本号
        id: extract_version
        run: |
          VERSION=$(echo "${{ github.event.pull_request.head.ref }}" | sed 's|release/v||')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: 获取变更内容
        id: extract_changelog
        run: |
          CHANGELOG=$(awk 'BEGIN {flag=0}
            /^## / {if (flag) exit; flag=1}
            flag {print}' CHANGELOG.md)
          
          echo "changelog<<EOF" >> "$GITHUB_OUTPUT"
          echo "$CHANGELOG" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: 创建Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.extract_version.outputs.version }}"
          name: "v${{ steps.extract_version.outputs.version }}"
          body: |
            ### 发布说明
            ${{ steps.extract_changelog.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
